# Generated by Django 3.2 on 2021-04-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
